source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'rspec-rails', '~> 3.1'
gem 'sqlite3'
gem 'minitest-rails', '~> 2.0'

group :development do
  gem 'spring'
end


group :test do
  gem 'minitest-rails-capybara'
  gem 'database_cleaner'
  gem 'capybara'
end
